# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "10.2.1"

    steps:
      - checkout

      # Setup
      - run:
          name: Bundle
          command: bundle install

      - run:
          name: Build dependencies
          command: make dependencies

      # - run:
      #     name: Test
      #     command: make test

      - run:
          name: Hub Detect
          command: ./hub-detect.sh
          when: always
          
      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs